server:
  port: 8080
  servlet:
    context-path: /

  ssl:
    key-store: keystore.p12
    key-store-password: 791346
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ynd?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ynd
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  devtools:
    livereload:
      enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

file:
  path: C:/src/SpringBootProStar/media/

